version: '3'
services:
  test-mysql:
    image: mysql:5.7
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      TZ: UTC
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3316:3306
    healthcheck:
      test: '/etc/init.d/mysql status'
      interval: 1s
      retries: 120