package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/leeduyoung/GraphQLServerTemplate/pkg/graph/gen"
	"github.com/leeduyoung/GraphQLServerTemplate/pkg/graph/gen/graphqlmodel"
	"github.com/leeduyoung/GraphQLServerTemplate/pkg/logger"
	"github.com/leeduyoung/GraphQLServerTemplate/pkg/storage"
)

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *graphqlmodel.Todo) (*graphqlmodel.User, error) {
	logger.Debug("Called User Resolver")

	return storage.GetUser(ctx, obj.UserID)
}

// Todo returns gen.TodoResolver implementation.
func (r *Resolver) Todo() gen.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
